
package com.futronic.workedex;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ACER-NOTE
 */
public class Formprincipal extends javax.swing.JFrame {

    /**
     * Creates new form Formprincipal
     */
    public Formprincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAlunos = new javax.swing.JButton();
        btnFuncioanrios = new javax.swing.JButton();
        btnMatriculas = new javax.swing.JButton();
        btnFrequencia = new javax.swing.JButton();
        JDesktopPane2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Itemfuncionario = new javax.swing.JMenu();
        MenuAluno = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        ItemMenuFichat = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        btnAlunos.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnAlunos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sgda/icones/alunos.png"))); // NOI18N
        btnAlunos.setText("Alunos");
        btnAlunos.setBorder(null);
        btnAlunos.setContentAreaFilled(false);
        btnAlunos.setFocusable(false);
        btnAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlunosActionPerformed(evt);
            }
        });

        btnFuncioanrios.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnFuncioanrios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sgda/icones/hiring.png"))); // NOI18N
        btnFuncioanrios.setText("Funcionários");
        btnFuncioanrios.setBorder(null);
        btnFuncioanrios.setContentAreaFilled(false);
        btnFuncioanrios.setFocusable(false);
        btnFuncioanrios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFuncioanriosActionPerformed(evt);
            }
        });

        btnMatriculas.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnMatriculas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sgda/icones/clipboard-with-pencil-.png"))); // NOI18N
        btnMatriculas.setText("Matriculas");
        btnMatriculas.setBorder(new javax.swing.border.MatteBorder(null));
        btnMatriculas.setContentAreaFilled(false);
        btnMatriculas.setFocusable(false);
        btnMatriculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatriculasActionPerformed(evt);
            }
        });

        btnFrequencia.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnFrequencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sgda/icones/calendar.png"))); // NOI18N
        btnFrequencia.setText("ALUNOS MATRICULADOS");
        btnFrequencia.setBorder(new javax.swing.border.MatteBorder(null));
        btnFrequencia.setContentAreaFilled(false);
        btnFrequencia.setFocusable(false);
        btnFrequencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFrequenciaActionPerformed(evt);
            }
        });

        JDesktopPane2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sgda/icones/6.png"))); // NOI18N

        Itemfuncionario.setText("Cadastrar");

        MenuAluno.setText("Aluno");
        MenuAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAlunoActionPerformed(evt);
            }
        });
        Itemfuncionario.add(MenuAluno);

        jMenuItem1.setText("Funcionário");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        Itemfuncionario.add(jMenuItem1);

        ItemMenuFichat.setText("Criar ficha");
        ItemMenuFichat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemMenuFichatActionPerformed(evt);
            }
        });
        Itemfuncionario.add(ItemMenuFichat);

        jMenuBar1.add(Itemfuncionario);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(btnFuncioanrios, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMatriculas, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFrequencia, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JDesktopPane2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMatriculas, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFuncioanrios, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFrequencia, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JDesktopPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(772, 640));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MenuAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAlunoActionPerformed
          CAluno s = new CAluno();
         JDesktopPane2.add(s);
          s.setVisible(true);
    }//GEN-LAST:event_MenuAlunoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        //  FormcFuncionario s = new FormcFuncionario();
        // s.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void ItemMenuFichatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemMenuFichatActionPerformed
        //   FormcFicha s = new FormcFicha();
        // s.setVisible(true);
    }//GEN-LAST:event_ItemMenuFichatActionPerformed

    private void btnAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlunosActionPerformed

        try {
            ListaAlunos s = new ListaAlunos();
            JDesktopPane2.add(s);
            s.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Formprincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(Formprincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAlunosActionPerformed

    private void btnFuncioanriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFuncioanriosActionPerformed
        //    FormlFuncionario s = new FormlFuncionario();
        //  s.setVisible(true);
    }//GEN-LAST:event_btnFuncioanriosActionPerformed

    private void btnMatriculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatriculasActionPerformed
       MatricularAluno s;
        try {
            s = new MatricularAluno();
            JDesktopPane2.add(s);
          s.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Formprincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
         
    }//GEN-LAST:event_btnMatriculasActionPerformed

    private void btnFrequenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFrequenciaActionPerformed
     FormTA t;
        try {
            t = new FormTA();
            JDesktopPane2.add(t);
          t.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Formprincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
         
        
        
        
        
    }//GEN-LAST:event_btnFrequenciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formprincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ItemMenuFichat;
    private javax.swing.JMenu Itemfuncionario;
    private javax.swing.JLabel JDesktopPane2;
    private javax.swing.JMenuItem MenuAluno;
    private javax.swing.JButton btnAlunos;
    private javax.swing.JButton btnFrequencia;
    private javax.swing.JButton btnFuncioanrios;
    private javax.swing.JButton btnMatriculas;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
