
package com.futronic.workedex;

import br.com.sgda.dao.AlunoDao;
import br.com.sgda.modelo.Pessoa;
import com.sun.jna.platform.win32.Sspi;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import util.Convert;
import util.GenericCalendar;

/**
 *
 * @author ACER-NOTE
 */
public class ListaAlunos extends javax.swing.JInternalFrame {

    private DateFormat format = new SimpleDateFormat("dd/MM/yyyy");
    /**
     * Creates new form ListaAlunos
     */
    public ListaAlunos() throws ClassNotFoundException, SQLException, Exception {
        initComponents();
        colocaNaTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfPESQUISAR = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAlunos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

        tfPESQUISAR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfPESQUISARKeyPressed(evt);
            }
        });

        jLabel1.setText("PESQUISAR CLIENTE");

        tblAlunos.setAutoCreateRowSorter(true);
        tblAlunos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 102)));
        tblAlunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOME", "CPF", "SEXO", "DATA DO CADASTRO"
            }
        ));
        jScrollPane1.setViewportView(tblAlunos);

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setText("EXCLUIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(tfPESQUISAR, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(43, 43, 43))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPESQUISAR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setBounds(0, 0, 732, 469);
    }// </editor-fold>//GEN-END:initComponents

    private void tfPESQUISARKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPESQUISARKeyPressed
        try {
            AlunoDao dao = new AlunoDao();
            List<Pessoa> alunoss = dao.buscaPorNome(tfPESQUISAR.getText());
            int linha = 0;
            DefaultTableModel dtm = (DefaultTableModel) tblAlunos.getModel();
            dtm.setNumRows(alunoss.size());
            for (Pessoa objforpessoa : alunoss) {
                tblAlunos.setValueAt(objforpessoa.getId(), linha, 0);
                tblAlunos.setValueAt(objforpessoa.getNome(), linha, 1);
                 tblAlunos.setValueAt(objforpessoa.getCpf(), linha, 2);
               
               String sexo = "FEMININO";
            if (objforpessoa.getSexo() == 1) {
                sexo = "MASCULINO";
            } 
            
            
                tblAlunos.setValueAt(sexo, linha, 3);
       
                linha++;
            }
        } catch (SQLException ex) {
            System.out.println("SQL erro: " + ex.getMessage());
        } catch (ClassNotFoundException ex) {
            System.out.println("Classe não encontrada: " + ex.getMessage());
        }
    }//GEN-LAST:event_tfPESQUISARKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        int resposta;
        resposta = JOptionPane.showConfirmDialog(null, "Deseja excluir o registro?","Confirme",JOptionPane.YES_NO_OPTION);
        if (resposta == 0){
            
            try {
                AlunoDao dao = new AlunoDao();            
                int registros = dao.getAlunos().size();             
                if (registros > 0){
                    int linha = tblAlunos.getSelectedRow();        
                    int id = (int)tblAlunos.getValueAt(linha,0);
                    dao.exluir(id);
                
                    DefaultTableModel dtm = 
                        (DefaultTableModel)tblAlunos.getModel();
                    dtm.removeRow(tblAlunos.getSelectedRow());
                    tblAlunos.setModel(dtm);
                    colocaNaTabela(); 
                }
            } catch (SQLException ex){
                Logger.getLogger(ListaAlunos.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
            Logger.getLogger(ListaAlunos.class.getName()).log(Level.SEVERE, null, ex);
           } catch (Exception ex) {
                Logger.getLogger(ListaAlunos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        
        /* 
        DefaultTableModel dtm = (DefaultTableModel)tblAlunos.getModel();
        if (tblAlunos.getSelectedRow() >= 0){
        dtm.removeRow(tblAlunos.getSelectedRow());
        tblAlunos.setModel(dtm);
        }else{
        JOptionPane.showMessageDialog(null, "Favor selecionar uma linha");
        } 
        */
      
    }//GEN-LAST:event_jButton1ActionPerformed

    
    public void colocaNaTabela() throws ClassNotFoundException, SQLException, Exception{      
        AlunoDao dao = new AlunoDao();
        List<Pessoa> alunoss = dao.getAlunos();
        int linha = 0;
        DefaultTableModel dtm = (DefaultTableModel) tblAlunos.getModel();
        dtm.setNumRows(alunoss.size());
        for (Pessoa pess : alunoss) {
            tblAlunos.setValueAt(pess.getId(), linha, 0);
            tblAlunos.setValueAt(pess.getNome(), linha, 1);
            tblAlunos.setValueAt(pess.getCpf(), linha, 2);
         //tblAlunos.setValueAt(pess.getSexo(), linha, 3);
         
             String sexo = "FEMININO";
            if (pess.getSexo() == 1) {
                sexo = "MASCULINO";
            } 

            
            tblAlunos.setValueAt(sexo, linha, 3);
            
            //tblAlunos.setValueAt(pess.getDataNascimento(), linha, 4);
            
            
          
            tblAlunos.setValueAt(Convert.convertDateToInterface(pess.getDataNascimento()), linha, 4);
            
           // tblAlunos.setValueAt(GenericCalendar.getCalendarCurrent(false),  linha, 4);
        

            
         
            linha++;
        }
       
    } 
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAlunos;
    private javax.swing.JTextField tfPESQUISAR;
    // End of variables declaration//GEN-END:variables
}
